# Generated by Django 3.1.3 on 2020-12-11 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cryptofolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settings',
            old_name='Currency',
            new_name='currency',
        ),
        migrations.RenameField(
            model_name='settings',
            old_name='Language',
            new_name='language',
        ),
    ]
