# Generated by Django 3.1.3 on 2020-12-03 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cryptofolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfoliocoin',
            old_name='userID',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='settings',
            old_name='userID',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='trades',
            old_name='userID',
            new_name='user',
        ),
    ]
