# Generated by Django 3.1.3 on 2020-12-01 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptofolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coinholding',
            name='comment',
            field=models.TextField(),
        ),
    ]
