# Generated by Django 3.1.3 on 2020-12-03 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cryptofolio', '0002_auto_20201203_1020'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Trades',
            new_name='Trade',
        ),
    ]
