# Generated by Django 3.1.3 on 2020-12-03 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptofolio', '0003_auto_20201203_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='tradetype',
            field=models.CharField(max_length=4),
        ),
    ]
