# Generated by Django 3.1.3 on 2020-12-03 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cryptofolio', '0004_auto_20201203_1052'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Portfoliocoin',
            new_name='Portfolio',
        ),
    ]
