# Generated by Django 3.1.3 on 2020-12-03 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cryptofolio', '0005_auto_20201203_1314'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='comment',
            new_name='note',
        ),
    ]
